### ISSUE TITLE
Refresh goes to Add credentials page, should just refresh index if on index.

### ISSUE THREAD

**Issue by Trimakas** [NafaaBout/bytestand#16]

**Comment by NafaaBout** [comment]
I do not see this error. But it can be because the amazon account is not set, in that case I made it explicitly redirect to add amazon account page.
Another thing to consider here, is that the full app is displayed within a iframe, so if you do a referesh of the full page, it will go to the index page. because that means you reopened the app again. and you can see that in the address bar, if you change page the url in the address bar does not change.
