### ISSUE TITLE
Amazon Pull doesn't seem to be working

### ISSUE THREAD

**Issue by Trimakas** [NafaaBout/bytestand#8]
Just hangs when I try it on my end.. from the terminal it looks like it gets queued but it doesn't seem to be running??

**Comment by NafaaBout** [comment]
you have to run sidekiq on a separate terminal.
just cd to the application folder and run `sidekiq`

On Thu, Oct 22, 2015 at 2:35 PM, Trimakas <notifications@github.com> wrote:

> Just hangs when I try it on my end.. from the terminal it looks like it
> gets queued but it doesn't seem to be running??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NafaaBout/bytestand/issues/8>.
>



-- 
Nafaa Boutefer
Ruby On Rails freelance developer
From Jijel Algeria.

   - Hire me on Upwork <https://www.upwork.com/users/~01f6a8667aea62d3a9>.
   - See my public work on Github: https://github.com/nafaabout
   - Follow me on Twitter: https://twitter.com/nafaabout

**Comment by Trimakas** [comment]
Got it running, but the process got killed for some reason? And the products were not displayed. Not sure why? Right now there are 2 of the same amazonaccounts..

**Comment by NafaaBout** [comment]
The process get killed because of the memory limit. the process needs more
memory, but your cloud 9 instance has only 512MB, which is not enough. This
is a problem in Ruby in general.

On Thu, Oct 22, 2015 at 3:13 PM, Trimakas <notifications@github.com> wrote:

> Got it running, but the process got killed for some reason? And the
> products were not displayed. Not sure why? Right now there are 2 of the
> same amazonaccounts..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NafaaBout/bytestand/issues/8#issuecomment-150237312>.
>



-- 
Nafaa Boutefer
Ruby On Rails freelance developer
From Jijel Algeria.

   - Hire me on Upwork <https://www.upwork.com/users/~01f6a8667aea62d3a9>.
   - See my public work on Github: https://github.com/nafaabout
   - Follow me on Twitter: https://twitter.com/nafaabout
